### ISSUE TITLE
android键盘遮挡输入框

### ISSUE THREAD

**Issue by pingxiaodou** [DaiYz/react-native-easy-chat-ui#13]
当在string.xml 设置了<item name="android:windowTranslucentStatus">true</item>时，键盘会遮挡输入框，请问有方法解决吗

**Comment by DaiYz** [comment]
@pingxiaodou Android键盘是原生自己控制，详细看ReadMe 最下面一行的Android键盘配置

**Comment by pingxiaodou** [comment]
@DaiYz 确实Android原生的问题，设置了沉浸式状态栏会导致adjustResize失效

**Comment by DaiYz** [comment]
@pingxiaodou 解决了么？

**Comment by pingxiaodou** [comment]
@DaiYz 只能先去掉沉浸式状态栏了

**Comment by DaiYz** [comment]
那这个应该是android原生的冲突了
