### ISSUE TITLE
多选时没有取消按钮功能

### ISSUE THREAD

**Issue by loss99** [DaiYz/react-native-easy-chat-ui#2]

**Comment by DaiYz** [comment]
@loss99 
 changeHeaderLeft: () => {
      /* example */
      // this.props.navigation.setParams({
      //   headerLeft: (
      //     <TouchableOpacity
      //       activeOpacity={0.7}
      //       style={{ top: 1, width: 54, paddingLeft: 12, justifyContent: 'center', alignItems: 'flex-start' }}
      //       onPress={() => {
      //         this.props.navigation.setParams({
      //           headerLeft: (
      //             <TouchableOpacity
      //               activeOpacity={0.7}
      //               style={{ top: 1, width: 54, paddingLeft: 8, justifyContent: 'center', alignItems: 'flex-start' }}
      //               onPress={() => this.props.navigation.goBack()}
      //             >
      //               <Material name={'keyboard-arrow-left'} size={30} color={'#000'} />
      //             </TouchableOpacity>
      //           )
      //         })
      //         that._closeMultipleSelect()
      //       }
      //       }
      //     >
      //       <Text style={{fontSize: 15, fontWeight: '600'}}>取消</Text>
      //     </TouchableOpacity>
      //   )
      // })
    },

可以使用此回调，以上是代码示例
