### ISSUE TITLE
gesture-handler编译报错

### ISSUE THREAD

**Issue by xiaokang-chen** [DaiYz/react-native-easy-chat-ui#26]
跑demo的时候在到react-native-gesture-handler编译的时候出错，报错如下：
**> Task :react-native-gesture-handler:compileDebugJavaWithJavac FAILED
FAILURE: Build failed with an exception.**

具体如下：
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerEnabledRootView.java:10: 错误: 找不到符号
import androidx.annotation.Nullable;
                          ^
  符号:   类 Nullable
  位置: 程序包 androidx.annotation
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\lib\src\main\java\com\swmansion\gesturehandler\GestureHandlerOrchestrator.java:14: 错误: 找不到符号
import androidx.annotation.Nullable;
                          ^
  符号:   类 Nullable
  位置: 程序包 androidx.annotation
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerEvent.java:3: 错误: 程序包androidx.core.util不存在
import androidx.core.util.Pools;
                         ^
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerEvent.java:11: 错误: 找不到符号
import androidx.annotation.Nullable;
                          ^
  符号:   类 Nullable
  位置: 程序包 androidx.annotation
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerEvent.java:19: 错误: 程序包Pools不存在
  private static final Pools.SynchronizedPool<RNGestureHandlerEvent> EVENTS_POOL =
                            ^
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.java:36: 错误: 找不到符号
import androidx.annotation.Nullable;
                          ^
  符号:   类 Nullable
  位置: 程序包 androidx.annotation
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerRegistry.java:11: 错误: 找不到符号
import androidx.annotation.Nullable;
                          ^
  符号:   类 Nullable
  位置: 程序包 androidx.annotation
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerPackage.java:16: 错误: 找不到符号
import androidx.annotation.Nullable;
                          ^
  符号:   类 Nullable
  位置: 程序包 androidx.annotation
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerRootInterface.java:3: 错误: 找不到符号
import androidx.annotation.Nullable;
                          ^
  符号:   类 Nullable
  位置: 程序包 androidx.annotation
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerRootView.java:10: 错误: 找不到符号
import androidx.annotation.Nullable;
                          ^
  符号:   类 Nullable
  位置: 程序包 androidx.annotation
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerRootViewManager.java:10: 错误: 找不到符号
import androidx.annotation.Nullable;
                          ^
  符号:   类 Nullable
  位置: 程序包 androidx.annotation
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerStateChangeEvent.java:3: 错误: 程序包androidx.core.util不存在
import androidx.core.util.Pools;
                         ^
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerStateChangeEvent.java:11: 错误: 找不到符号
import androidx.annotation.Nullable;
                          ^
  符号:   类 Nullable
  位置: 程序包 androidx.annotation
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerStateChangeEvent.java:19: 错误: 程序包Pools不存在
  private static final Pools.SynchronizedPool<RNGestureHandlerStateChangeEvent> EVENTS_POOL =
                            ^
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerEnabledRootView.java:14: 错误: 找不到符号
  private @Nullable ReactInstanceManager mReactInstanceManager;
           ^
  符号:   类 Nullable
  位置: 类 RNGestureHandlerEnabledRootView
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerEnabledRootView.java:15: 错误: 找不到符号
  private @Nullable RNGestureHandlerRootHelper mGestureRootHelper;
           ^
  符号:   类 Nullable
  位置: 类 RNGestureHandlerEnabledRootView
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerEnabledRootView.java:63: 错误: 找不到符号
          @Nullable Bundle initialProperties) {
           ^
  符号:   类 Nullable
  位置: 类 RNGestureHandlerEnabledRootView
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\lib\src\main\java\com\swmansion\gesturehandler\GestureHandlerOrchestrator.java:321: 错误: 找不到符号
  private boolean isViewAttachedUnderWrapper(@Nullable View view) {
                                              ^
  符号:   类 Nullable
  位置: 类 GestureHandlerOrchestrator
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerEvent.java:24: 错误: 找不到符号
          @Nullable RNGestureHandlerEventDataExtractor dataExtractor) {
           ^
  符号:   类 Nullable
  位置: 类 RNGestureHandlerEvent
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerEvent.java:40: 错误: 找不到符号
          @Nullable RNGestureHandlerEventDataExtractor dataExtractor) {
           ^
  符号:   类 Nullable
  位置: 类 RNGestureHandlerEvent
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.java:529: 错误: 找不到符号
  public @Nullable Map getConstants() {
          ^
  符号:   类 Nullable
  位置: 类 RNGestureHandlerModule
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.java:632: 错误: 找不到符号
  private @Nullable RNGestureHandlerRootHelper findRootHelperForViewAncestor(int viewTag) {
           ^
  符号:   类 Nullable
  位置: 类 RNGestureHandlerModule
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.java:649: 错误: 找不到符号
  private @Nullable HandlerFactory findFactoryForHandler(GestureHandler handler) {
           ^
  符号:   类 Nullable
  位置: 类 RNGestureHandlerModule
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerRegistry.java:23: 错误: 找不到符号
  public synchronized @Nullable GestureHandler getHandler(int handlerTag) {
                       ^
  符号:   类 Nullable
  位置: 类 RNGestureHandlerRegistry
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerRootInterface.java:6: 错误: 找不到符号
  @Nullable RNGestureHandlerRootHelper getRootHelper();
   ^
  符号:   类 Nullable
  位置: 接口 RNGestureHandlerRootInterface
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerRootView.java:14: 错误: 找不到符号
  private @Nullable RNGestureHandlerRootHelper mRootHelper;
           ^
  符号:   类 Nullable
  位置: 类 RNGestureHandlerRootView
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerRootViewManager.java:42: 错误: 找不到符号
  public @Nullable Map getExportedCustomDirectEventTypeConstants() {
          ^
  符号:   类 Nullable
  位置: 类 RNGestureHandlerRootViewManager
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerStateChangeEvent.java:26: 错误: 找不到符号
          @Nullable RNGestureHandlerEventDataExtractor dataExtractor) {
           ^
  符号:   类 Nullable
  位置: 类 RNGestureHandlerStateChangeEvent
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerStateChangeEvent.java:44: 错误: 找不到符号
          @Nullable RNGestureHandlerEventDataExtractor dataExtractor) {
           ^
  符号:   类 Nullable
  位置: 类 RNGestureHandlerStateChangeEvent
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\lib\src\main\java\com\swmansion\gesturehandler\GestureHandlerOrchestrator.java:328: 错误: 找不到符号
    @Nullable ViewParent parent = view.getParent();
     ^
  符号:   类 Nullable
  位置: 类 GestureHandlerOrchestrator
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerEvent.java:20: 错误: 程序包Pools不存在
          new Pools.SynchronizedPool<>(TOUCH_EVENTS_POOL_SIZE);
                   ^
C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerStateChangeEvent.java:20: 错误: 程序包Pools不存在
          new Pools.SynchronizedPool<>(TOUCH_EVENTS_POOL_SIZE);
                   ^
注: C:\Users\34662\Desktop\react-native-easy-chat-ui-master\Demo\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerButtonViewManager.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
32 个错误

**Comment by DaiYz** [comment]
没有问题，请检查自己的服务，确定是否开错
