### ISSUE TITLE
运行例子的时候报错

### ISSUE THREAD

**Issue by xiaokang-chen** [DaiYz/react-native-easy-chat-ui#27]
null is not an object(evaluating 'AudioRecorderManager.checkAuthorizationStatus')。我猜想是调用react-native-audio的授权时候有问题。但是不知道该怎么解决呀

**Comment by xiaokang-chen** [comment]
还有一个问题就是表情和更多功能的加号，点击后出现的功能栏高度要是能和键盘高一样就更好了

**Comment by DaiYz** [comment]
高度可以自己改
