### ISSUE TITLE
上滑取消发送，不太灵敏

### ISSUE THREAD

**Issue by 13244420529** [DaiYz/react-native-easy-chat-ui#28]
您好，请问一下，在发送语音时，上滑取消，不太灵敏，总是在取消和发送之间跳，有时候还取消不了，能给出点建议吗

**Comment by DaiYz** [comment]
android 还是iOS啊

**Comment by DaiYz** [comment]
已修复，请更新到最新版本

**Comment by 13244420529** [comment]
好的，才看到，真辛苦，谢谢了

在 2019-09-07 16:01:51，"DaiYz" <notifications@github.com> 写道：


已修复，请更新到最新版本
