### ISSUE TITLE
当长按多选删除时，删除消息后删除按钮没有消失

### ISSUE THREAD

**Issue by 13244420529** [DaiYz/react-native-easy-chat-ui#32]
您好，请问一下，当长按多选删除时，删除消息后删除按钮没有消失，这个我得调用哪个事件来处理，然后还有左侧的选中状态按钮，刚开始多选时默认选中一个，那么我将其不选中，就是一个选中的都没有，此时删除按钮还是可以点击，这个我得需要怎么处理一下呢，谢谢了，我这是个新手。

**Comment by DaiYz** [comment]
调用内部方法

**Comment by DaiYz** [comment]
源码有个注释掉的例子，你可以看下

**Comment by 13244420529** [comment]
谢谢啦
