### ISSUE TITLE
非常感谢，很好用，希望能把style部分抽取出来，这样方便统一定制主题

### ISSUE THREAD

**Issue by yangfanyu** [DaiYz/react-native-easy-chat-ui#33]
非常感谢，很好用，希望能把各控件的style部分统一到一个模块，这样方便统一定制主题，也方便调整一些尺寸参数（有些地方尺寸不是很精确）
![WechatIMG5](https://user-images.githubusercontent.com/17940584/65458650-a3fda500-de80-11e9-8208-b55ca8b89ce4.jpeg)

**Comment by DaiYz** [comment]
已修复样式问题，关于主题你有什么方案可以提一个PR
