### ISSUE TITLE
发送语音或者图片，前面的loading不消失

### ISSUE THREAD

**Issue by 13244420529** [DaiYz/react-native-easy-chat-ui#34]
当发送语音时先将sendStatus设置为0此时有loading，当消息真正发出去后，动态改变该消息的sendStatus为1时，还是有loading，我用setState来改变的，render也执行了，loading一直在，同样的代码，我发送纯文本时先有loading，发送成功后loading消失，这个有遇到过吗，还是我的思路不对，请求指点一下哈哈

**Comment by DaiYz** [comment]
需要深拷贝

**Comment by 13244420529** [comment]
非常感谢，问题解决啦
