### ISSUE TITLE
delPanel将android 设备识别成iphonex了，导致最底部消息被挡住

### ISSUE THREAD

**Issue by yangfanyu** [DaiYz/react-native-easy-chat-ui#35]
小米mix3 :

![WechatIMG6](https://user-images.githubusercontent.com/17940584/65505300-79046700-defb-11e9-9856-c8a170f58efa.jpeg)

现在我是通过设置样式强制解决的，不知道有没有什么好办法：

`
delPanelStyle={{position: 'absolute', bottom: 0, right: 0, left: 0, paddingBottom: Theme.screenInset.bottom}}
`
Theme.screenInset.bottom是自己算出来的屏幕底部距离，修改后正常了：

![WechatIMG7](https://user-images.githubusercontent.com/17940584/65505512-f4feaf00-defb-11e9-9259-a3b2229501c5.jpeg)

**Comment by yangfanyu** [comment]
不行啊，这样改了，最下面的消息左边的删除圈圈点不了，估计被透明区域盖住了

**Comment by DaiYz** [comment]
很奇怪这个bug,你可以看下我判断iPhoneX的方法，我是先判断了是否是iOS

**Comment by DaiYz** [comment]
你能不能copy出那个判断iPhoneX的代码然后用你的手机帮我测下这个bug，我不知道是不是判断平台出现了错误，谢谢！

**Comment by yangfanyu** [comment]
> 你能不能copy出那个判断iPhoneX的代码然后用你的手机帮我测下这个bug，我不知道是不是判断平台出现了错误，谢谢！

`const isIPhoneX = () => {
  return (
    (Platform.OS === 'ios' &&
      ((D_HEIGHT === X_HEIGHT && D_WIDTH === X_WIDTH) ||
        (D_HEIGHT === X_WIDTH && D_WIDTH === X_HEIGHT))) ||
    ((D_HEIGHT === XSMAX_HEIGHT && D_WIDTH === XSMAX_WIDTH) ||
      (D_HEIGHT === XSMAX_WIDTH && D_WIDTH === XSMAX_HEIGHT))
  )
}`

平台判断没有问题，应该是布局的原因

**Comment by yangfanyu** [comment]
![131569393755_ pic_hd](https://user-images.githubusercontent.com/17940584/65575581-bff96780-dfa2-11e9-8660-346a4d22063a.jpg)

del/index.js 这两个地方可能有点问题

**Comment by DaiYz** [comment]
ok, 我大致明白了

**Comment by DaiYz** [comment]
已修复
