### ISSUE TITLE
关于消息列表的内存优化建议

### ISSUE THREAD

**Issue by yangfanyu** [DaiYz/react-native-easy-chat-ui#36]
首先我设置inverted={true}，该值为false时载入界面会自动播放N长时间的往下滚动动画（不知是不是bug）
初始载入1000条消息的情况（注意views数量）：

![WechatIMG8](https://user-images.githubusercontent.com/17940584/65513012-f5ec0c80-df0c-11e9-9b9d-5c9be5449b14.jpeg)

往上滑动一段距离后，views数量增长了极多，而且不会降下来:

![WechatIMG9](https://user-images.githubusercontent.com/17940584/65513073-1caa4300-df0d-11e9-8a59-ddf91edc52ab.jpeg)

**另外，长按多选时，消息多了明显卡顿。**

--------------分割线---------------------

之后我在源码中flatlist的渲染处加上了removeClippedSubviews={true}，初始化载入情况:

![101569329614_ pic_hd](https://user-images.githubusercontent.com/17940584/65513247-832f6100-df0d-11e9-824c-0b88744cbedb.jpg)

往上滑动一段距离后，views数量基本不变:

![111569329653_ pic_hd](https://user-images.githubusercontent.com/17940584/65513300-9e01d580-df0d-11e9-85d4-fbbe8511c946.jpg)

是否可加上一些flatlist优化参数的配置入口

**Comment by DaiYz** [comment]
首先 以最新消息一定是最后一条为原则 当inverted= false ，进入聊天界面，为了能快速到达最新一条消息是有一个滚动到底部的动画，消息多的话肯定会卡顿，你应当考虑在列表超过屏幕的时候，下次在进入聊天界面采用倒排形式即inverted= true

**Comment by DaiYz** [comment]
已加属性flatListProps
