### ISSUE TITLE
消息发送失败时，也会显示已读

### ISSUE THREAD

**Issue by 13244420529** [DaiYz/react-native-easy-chat-ui#37]
您好，消息已读会不会存在一个问题，我先发送一条消息，假如失败了，那么此时肯定还是未读，那么我又发送一条消息，假如本次成功了，会显示已读，咱们这个显示已读是根据最后读取时间来判断的，那就回导致我上一个失败的也会显示已读，然后还有发送语音时，正常是对方听过后显示已读，假如我发送一个语音，紧接着又发送一个文本消息，文本一进页面就会显示已读，最后读取时间定位到文本，那语音此时也会显示已读，如果能将消息已读，未读，定位到每一个消息就好了，比如消息对象中本身就存在一个状态。

**Comment by DaiYz** [comment]
自己去改属性

**Comment by 13244420529** [comment]
我这没太理解你说的啊

**Comment by DaiYz** [comment]
更新到最新版本，可以关掉这个功能，具体你可以看下源码
