### ISSUE TITLE
点击加号图标闪退

### ISSUE THREAD

**Issue by gitspringcould** [DaiYz/react-native-easy-chat-ui#38]

**Comment by gitspringcould** [comment]
点击加号折叠功能区，app闪退

**Comment by DaiYz** [comment]
能提供下具体报错信息吗？

**Comment by gitspringcould** [comment]
Honor 8 Lite无报错，直接闪退


------------------ 原始邮件 ------------------
发件人: "DaiYz"<notifications@github.com>;
发送时间: 2019年10月8日(星期二) 上午9:17
收件人: "DaiYz/react-native-easy-chat-ui"<react-native-easy-chat-ui@noreply.github.com>;
抄送: "何某人"<1162487568@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [DaiYz/react-native-easy-chat-ui] 点击加号图标闪退 (#38)




Reopened #38.

**Comment by DaiYz** [comment]
闪退是源码报错了，看下logcat
