### ISSUE TITLE
多选后，点击左上角取消可以关闭多选，但是再执行一次多选有问题

### ISSUE THREAD

**Issue by 13244420529** [DaiYz/react-native-easy-chat-ui#40]
多选后，会有一个选中，并且左侧图标是勾选状态，点击左上角取消可以关闭多选，但是再执行一次多选后，也会有一个选中，但是左侧图标不是勾选状态，我看了一下源码
componentWillReceiveProps (nextProps) {
    if (!nextProps.isOpen) {
      this.setState({ isSelect: false })
    } else {
      if (nextProps.currentIndex === parseInt(nextProps.rowId) && this.props.currentIndex !== parseInt(nextProps.rowId)) {
        this.setState({ isSelect: true })
      }
    }
  }

再次执行多选时this.props.currentIndex !== parseInt(nextProps.rowId) 是false，导致无法执行this.setState({ isSelect: true })，所以没勾选上，这个希望您能够给点建议，或者修改一下，谢谢啦

**Comment by 13244420529** [comment]
![image](https://user-images.githubusercontent.com/52736374/66880364-2c411700-eff5-11e9-943a-e972816c272e.png)

第二次
![image](https://user-images.githubusercontent.com/52736374/66880378-3e22ba00-eff5-11e9-91f3-53a7593ca2c6.png)

**Comment by DaiYz** [comment]
好的，我明天有空看下

**Comment by DaiYz** [comment]
已修复

**Comment by 13244420529** [comment]
好的，多谢了
