### ISSUE TITLE
如何获取消息是否超过一屏

### ISSUE THREAD

**Issue by 13244420529** [DaiYz/react-native-easy-chat-ui#42]
您好，我该如何获取消息是否超过一屏，我看源码
onLayout={(e) => {
  this._scrollToBottom()
  this.listHeight = e.nativeEvent.layout.height
 }}
onContentSizeChange={(contentWidth, contentHeight) => { this._scrollToBottom({ contentWidth, contentHeight }) }}
只有这两个地方操作了高度
_scrollToBottom (listHeightAndWidth) {
    const { inverted } = this.props
    if (listHeightAndWidth !== undefined) {
      const { contentHeight } = listHeightAndWidth
      this.isInverted = contentHeight > this.listHeight
    }
    if (!inverted) {
      setTimeout(() => {
        this.chatList && this.chatList.scrollToEnd({
          animated: this._userHasBeenInputed
        })
      }, this._userHasBeenInputed ? 0 : 130)
    }
  }

contentHeight 是内容高度是吧，那我外部得怎么获取呢
this.state = {
     . . .
    contentHeight: 0，
    . . .
}
我是利用
<ChatScreen
          ref={(e) => this.chat = e}
 this.chat外部获取这个高度，但是始终是0，因为没有任何地方改变这个state，是不是我的想法有问题，希望给点建议，谢谢了

**Comment by DaiYz** [comment]
发送方法的参数里有

**Comment by 13244420529** [comment]
那例如：
A用户给B用户发送消息，A通过发送方法可以判断是否倒置，但是B用户他只是接收消息啊，这个怎么判断是否倒置

**Comment by 13244420529** [comment]
我自定义setPopItems的时候删除走的是自己的方法，这里是没有倒置的，我该怎么处理呢
![image](https://user-images.githubusercontent.com/52736374/67911566-00f82380-fbc2-11e9-8542-01ea1702eadf.png)

**Comment by 13244420529** [comment]
删除的时候的isInverted这个参数有很大误差啊

**Comment by 13244420529** [comment]
如果我自定义了setPopItems，那么this.props.delMessage({ index, message }, this.isInverted)中的this.isInverted我只能通过this.chat.isInverted去拿对吧
show = (view, type, index, text, message) => {
    if (!this.props.usePopView) {
      this.props.onMessageLongPress(type, index, text, message)
    } else {
      view.measure((x, y, width, height, pageX, pageY) => {
        let items = null
        if (this.props.setPopItems) {
          items = this.props.setPopItems(type, index, text, message)
        } else {
          items = [
            {
              title: '删除',
              onPress: () => {
                this.props.delMessage({ index, message }, this.isInverted)
