### ISSUE TITLE
ViewPagerAndroid has been removed from React Native

### ISSUE THREAD

**Issue by xjy0925** [DaiYz/react-native-easy-chat-ui#43]
react native 6.1版本, 报了这个错误.
Invariant Violation: ViewPagerAndroid has been removed from React Native. It can now be installed and imported from 'react-native-viewpager' instead of 'react-native'. See https://github.com/react-native-community/react-native-viewpager

This error is located at:
    in EmojiPanel (at ChatView.js:1124)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at ChatView.js:956)
    in RCTView (at ChatView.js:954)

**Comment by DaiYz** [comment]
OK

**Comment by DaiYz** [comment]
你先自己改下这一块

**Comment by DaiYz** [comment]
已修复
