### ISSUE TITLE
除了发送，删除操作能获取是否超过一屏，还有别的方式吗

### ISSUE THREAD

**Issue by 13244420529** [DaiYz/react-native-easy-chat-ui#44]
1、那例如：
A用户给B用户发送消息，A通过发送方法可以判断是否倒置，但是B用户他只是接收消息啊，这个怎么判断是否倒置

2、删除的时候的isInverted这个参数有很大误差啊

3、如果我自定义了setPopItems，那么this.props.delMessage({ index, message }, this.isInverted)中的this.isInverted我只能通过this.chat.isInverted去拿对吧
show = (view, type, index, text, message) => {
if (!this.props.usePopView) {
this.props.onMessageLongPress(type, index, text, message)
} else {
view.measure((x, y, width, height, pageX, pageY) => {
let items = null
if (this.props.setPopItems) {
items = this.props.setPopItems(type, index, text, message)
} else {
items = [
{
title: '删除',
onPress: () => {
this.props.delMessage({ index, message }, this.isInverted)

**Comment by DaiYz** [comment]
你为何频繁修改isInverted这个属性呢？

**Comment by 13244420529** [comment]
发送消息时方发送超过一屏了我可以通过这个参数改变，那我自定义删除功能时，当我消息已经删除的不足一屏是我肯定得把这个参数修改一下，假如接收者，他的数据超过一屏了，但是没有触发发送和删除功能，那他无法修改这个参数啊对吧

**Comment by 13244420529** [comment]
我看了一下源码，然后自己添加了一个属性 getIsInverted:PropTypes.func， 来提供给外部进行获取
 _scrollToBottom (listHeightAndWidth) {
    // 自定义获得是否倒置方法 getIsInverted 
    const { inverted, getIsInverted } = this.props
    if (listHeightAndWidth !== undefined) {
      const { contentHeight } = listHeightAndWidth
      this.isInverted = contentHeight > this.listHeight
      // 调用此方法
      getIsInverted(this.isInverted);
    }
    if (!inverted) {
      setTimeout(() => {
        this.chatList && this.chatList.scrollToEnd({
          animated: this._userHasBeenInputed
        })
      }, this._userHasBeenInputed ? 0 : 130)
    }
  }

**Comment by DaiYz** [comment]
这个属性不是这么用的

**Comment by 13244420529** [comment]
那尴尬了，我这不太了解哈，那这个属性怎么用的啊，那我页面刚开始进来时怎么知道是否是倒置呢

**Comment by 13244420529** [comment]
我没有改this.isInverted这个值，我只是想从父组件中获取这个倒置状态，然后存储起来

**Comment by DaiYz** [comment]
你聊天没做本地数据存储？开屏没做数据装载？

**Comment by 13244420529** [comment]
我做本地存储啦，如果先不设置这个FlagList这个倒置属性他会从上到下有个加载的动画效果，然后才能到达底部，我现在不知道刚进入页面数据加载时怎么设置这个属性

**Comment by 13244420529** [comment]
![image](https://user-images.githubusercontent.com/52736374/68100820-2dcf7200-ff05-11e9-8255-00ea22556eb7.png)

**Comment by 13244420529** [comment]
假如说我发送放发送20条消息后，能通过sendMessage中的参数知道该倒置了，但是接收方一下子有20条数据，在刚进页面时就有一个加载动画，然后才能到达底部，这个时候就应该获取是否超过一屏，我不知道怎么获取啊

**Comment by DaiYz** [comment]
没有聊天数据用false啊，没必要到底部，如果说你是接收方，你自己斟酌下收到的信息数量就行了，比如一下收到了200条，那你觉得会不会超过一屏幕？

**Comment by DaiYz** [comment]
20条倒不倒置随你，一般十条就超屏幕了

**Comment by 13244420529** [comment]
但是这个也不是绝对的啊，每条消息都不一样高啊，假如是图片可能5条消息就该倒置了，可能文本消息还没有倒置啊，总不能根据消息条数来判断啊

**Comment by DaiYz** [comment]
你自己测试下消息

**Comment by 13244420529** [comment]
啊啊啊，那我明白你的意思了，你说的有道理哈，行，那我去操作了，谢谢啦，这么耐心的指导

**Comment by DaiYz** [comment]
20条以内信息倒不倒置都可以，性能是够的，我测试了所有机型，纯文本的话10条绝对是超的

**Comment by 13244420529** [comment]
好的，知道了，太感谢你了，这个插件感觉做的非常好，给你个大赞哈哈
