### ISSUE TITLE
no such file or directory,  '/Users/user/folder/source'  Failed building JavaScript bundle.

### ISSUE THREAD

**Issue by presola** [DaiYz/react-native-easy-chat-ui#45]
When using expo, i am unable to start my app because it throws 
```
ENOENT: no such file or directory, scandir '/Users/abisola/Downloads/bereno-app/source'
Failed building JavaScript bundle.
```
After searching my app source i discovered it is because **react-native-easy-chat-ui** uses relative paths in it's code base e.g ../../source.

If i remove this package, all works well. I use expo to start my react app.
Please help, here is my package.json

[package.txt](https://github.com/DaiYz/react-native-easy-chat-ui/files/3797824/package.txt)

**Comment by DaiYz** [comment]
What is your version of expo

**Comment by DaiYz** [comment]
[You can look at this and maybe it will help you](https://forums.expo.io/t/enoent-no-such-file-or-directory-scandir-error-on-loading-app/23720)

**Comment by presola** [comment]
Unfortunately, that doesn't help because it's related to expo vector icons and its fixed in the package itself. I am having the issue with the react native easy chat ui

**Comment by DaiYz** [comment]
Em....  very strange. I just tried expo and found no mistakes. 😢

**Comment by presola** [comment]
@DaiYz , are you using sdk 0.35.0

**Comment by DaiYz** [comment]
Yes, sure
