### ISSUE TITLE
发送文本消息时显示错误

### ISSUE THREAD

**Issue by 13244420529** [DaiYz/react-native-easy-chat-ui#46]
您好，我在发送消息时出现点问题，例如：
我发送的消息为[xxxxxx]这个时候会出现以下情况
![image](https://user-images.githubusercontent.com/52736374/68064849-1b660480-fd5c-11e9-8076-8c990952f280.png)
![image](https://user-images.githubusercontent.com/52736374/68064855-2c167a80-fd5c-11e9-9db3-3b97a4eabc92.png)
希望您可以解决一下

**Comment by DaiYz** [comment]
已修复
