### ISSUE TITLE
下拉加载历史记录问题

### ISSUE THREAD

**Issue by ljh740** [DaiYz/react-native-easy-chat-ui#47]
实现了loadHistory方法,但是下拉并任何反应?也没有触发loadHistory?

<ChatScreen
          ref={(e) => this.chat = e}
          messageList={this.state.messages}
          sendMessage={this.sendMessage}
          reSendMessage={this.reSendMessage}
          userProfile={this.state.userProfile}
          chatId={this.state.chatInfo.id}
          loadHistory={this.loadHistory}
      />

**Comment by DaiYz** [comment]
倒排才能触发

**Comment by DaiYz** [comment]
inverter 为true时候才会触发，不然是触发的下面
