### ISSUE TITLE
Android设备，delPanel没有到达最底部

### ISSUE THREAD

**Issue by 13244420529** [DaiYz/react-native-easy-chat-ui#49]
您好，我这现在遇到一个问题，长按多选时删除面板没有到达最底部
荣耀play：
![1](https://user-images.githubusercontent.com/52736374/71428228-7122b180-26fa-11ea-9fe8-1bce7084cca1.jpg)

mate30：
![2](https://user-images.githubusercontent.com/52736374/71428232-754ecf00-26fa-11ea-90b4-7218a1970cb8.jpg)

**Comment by 13244420529** [comment]
![1](https://user-images.githubusercontent.com/52736374/71428203-420c4000-26fa-11ea-9d7f-91e267059f76.jpg)

**Comment by DaiYz** [comment]
![image](https://user-images.githubusercontent.com/28336215/71452462-3edb8780-27c0-11ea-9f3b-10459bc83687.png)
文件路径：app -> chat -> del -> index.js 帮我定位下这里的top 具体值是不是有误，目前我没有测试机

**Comment by DaiYz** [comment]
你Android是不是开了沉浸式？

**Comment by 13244420529** [comment]
行，我去看看，是沉浸式

**Comment by DaiYz** [comment]
那就是沉浸式Android的导航头有问题，你自己要重新计算下

**Comment by DaiYz** [comment]
你计算好HeaderHeight这个属性的值

**Comment by 13244420529** [comment]
啊啊啊，知道啦
![image](https://user-images.githubusercontent.com/52736374/71495368-6a29a980-2888-11ea-820a-f187b4a80a84.png)
我这要计算androidHeaderHeight 就可以了是吧然后传递一下

**Comment by DaiYz** [comment]
对的，我例子是从react-navigation的方法里拿的，如果你是沉浸式的话，屏幕高度计算与导航头是不一样的

**Comment by 13244420529** [comment]
这个我得怎么计算呢，能讲解一下吗，我不是太懂，多谢啦

**Comment by DaiYz** [comment]
![image](https://user-images.githubusercontent.com/28336215/71497880-13769c80-2895-11ea-88b6-7c7fd273a6a8.png)
如果你这么写的话就是错的
去掉加号后面的

**Comment by 13244420529** [comment]
我在模拟器测试
![image](https://user-images.githubusercontent.com/52736374/71498398-330ec480-2897-11ea-9fd0-619acc04b872.png)

真机上
![2](https://user-images.githubusercontent.com/52736374/71498470-79fcba00-2897-11ea-959f-d892e683172d.jpg)

**Comment by DaiYz** [comment]
以真机为准

**Comment by 13244420529** [comment]
我刚开是用的真机是Android刘海屏的，现在用另一个没有刘海的，但是跟模拟器是一样的
![1](https://user-images.githubusercontent.com/52736374/71498848-00fe6200-2899-11ea-9fac-3f43055e4bb9.png)

**Comment by 13244420529** [comment]
![1](https://user-images.githubusercontent.com/52736374/71498877-25f2d500-2899-11ea-99b8-d8585ad2c2a7.png)

**Comment by DaiYz** [comment]
那你要考虑刘海屏幕的计算，自己算下吧

**Comment by 13244420529** [comment]
嗯嗯，那好的，多谢啦

**Comment by DaiYz** [comment]
把你Android高度的代码贴出来看看

**Comment by DaiYz** [comment]
也就是说没有刘海屏多减了

**Comment by 13244420529** [comment]
![image](https://user-images.githubusercontent.com/52736374/71499018-b3cec000-2899-11ea-9ccb-c16033fdec0e.png)

**Comment by DaiYz** [comment]
那你打印下这个值，应该是刘海屏与非刘海屏机制不一样

**Comment by 13244420529** [comment]
我刚才打印了一下，值是一样的

**Comment by DaiYz** [comment]
是多少

**Comment by 13244420529** [comment]
都是56

**Comment by 13244420529** [comment]
如果想往上移动的话，这个值得大一些吧。

**Comment by DaiYz** [comment]
我在改

**Comment by DaiYz** [comment]
沉浸式情况下，你点击右下脚的加号，是不是也会出问题

**Comment by DaiYz** [comment]
表情面板有问题吗？

**Comment by 13244420529** [comment]
这个还没发现有什么问题
![1](https://user-images.githubusercontent.com/52736374/71505220-61040100-28b7-11ea-8df9-4a48cd204a2a.jpg)

**Comment by DaiYz** [comment]
好了，更新到最新版本

**Comment by 13244420529** [comment]
ok，已经没问题了，多谢啦

**Comment by DaiYz** [comment]
刘海屏幕跟普通的都测试了吗？
