### ISSUE TITLE
能添加上视频消息功能吗?

### ISSUE THREAD

**Issue by loss99** [DaiYz/react-native-easy-chat-ui#5]

**Comment by DaiYz** [comment]
@loss99 只是添加渲染单个消息的样式，具体实现功能参照panelSource 和 renderPanelRow 属性

**Comment by loss99** [comment]
请问 为什么 使用的是ListView 


不是 Flatlist?
不是说 后者更 高效吗?


我在使用 的时候 从对话列表跳转到 对话界面的时候 会有白屏大概 0.5 秒 然后 对话页面才开始 加载数据
请问 从哪方面优化?
this.state = {}


和  state = {msg:{}}


没什么 区别吧


在2018年11月21日 09:18，DaiYz<notifications@github.com> 写道：

@loss99 只是添加渲染单个消息的样式，具体实现功能参照panelSource 和 renderPanelRow 属性
