### ISSUE TITLE
This package is not working in recent React Native version....

### ISSUE THREAD

**Issue by rising32** [DaiYz/react-native-easy-chat-ui#50]
"react": "16.9.0",
"react-native": "0.61.5"

error message is as following...
 WARN  Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: ChatItem, EmojiPanel, PlusPanel, VoiceMessage

Please help me quickly....

**Comment by DaiYz** [comment]
please update to 0.4.2

**Comment by rising32** [comment]
![image](https://user-images.githubusercontent.com/29010143/71453254-3fc2e800-27c5-11ea-8a0a-26165cb9532a.png)

**Comment by DaiYz** [comment]
OK

**Comment by rising32** [comment]
![image](https://user-images.githubusercontent.com/29010143/71453898-c927e980-27c8-11ea-9441-e12ba243d213.png)

import React from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  StatusBar,
  PermissionsAndroid,
  TouchableOpacity,
  Dimensions
} from 'react-native';
import {ChatScreen} from 'react-native-easy-chat-ui'
import FastImage from 'react-native-fast-image'
import RNFS from 'react-native-fs'
import {AudioRecorder, AudioUtils} from 'react-native-audio'
import { Player, Recorder, MediaStates } from '@react-native-community/audio-toolkit';
import { useState, useEffect } from 'react';
import { initialMessages, initialPanelSource } from './message';
const { width, height } = Dimensions.get('window')

const App = () => {
  const [messages, setMessages] = useState(initialMessages);
  const [chatBg, setChatBg] = useState(require('./assets/images/bg.jpg'));
  const [inverted, setInverted] = useState(false);  //When messageList exceeds the screen height, set it to true otherwise false (You can change this value when componentWillUnmount or delete message)
  
  const [voiceHandle, setVoiceHandle] = useState(true);  // Whether to get a recording handle
  const [currentTime, setCurrentTime]  = useState(0);   // audio length
  const [audioPath,setAudioPath] = useState('');   //File path to store voice
  const [hasPermission, setHasPermission] = useState(false);
  const [voicePlaying, setVoicePlaying] = useState(false);  //Playing voice or not
  const [voiceLoading, setVoiceLoading] = useState(false);   // Loading voice or not
  const [voiceVolume, setVoiceVolume] = useState(0);  // Volume (0~10)
  const [volume, setVolume] = useState(0);
  const [timer, setTimer] = useState(0);
  const [finished, setFinished] = useState(true);
  const panelSource = [
    {
      icon: (
        <FastImage
          source={require('./assets/images/photo.png')}
          style={{width: 30, height: 30}}
        />
      ),
      title: '照片',
    },
    {
      icon: (
        <FastImage
          source={require('./assets/images/camera.png')}
          style={{width: 30, height: 30}}
        />
      ),
      title: '拍照',
    },
  ];   // Custom panel source
  const [error, setError] = useState(null);
  const [player, setPlayer] = useState(null);
  const [recorder, setRecorder] = useState(null);

  const sendMessage = (type, content, isInverted) => {
    const newMsg = [...messages];
    newMsg.push({
      id: `${new Date().getTime()}`,
      type,
      content,
      targetId: '88886666',
      chatInfo: {
        avatar: require('./assets/images/avatar.png'),
        id: '12345678',
        nickName: 'Test',
      },
      renderTime: true,
      sendStatus: 1,
      time: `${new Date().getTime()}`,
    });
    setMessages(newMsg);
  };
  const renderPanelRow = (data, index) => (
    <TouchableOpacity
      key={index}
      style={{
        width: (width - 30) / 4,
        height: (width - 30) / 4,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
      }}
      activeOpacity={0.7}
      onPress={() => console.log('press')}>
      <View
        style={{
          backgroundColor: '#fff',
          borderRadius: 8,
          padding: 15,
          borderColor: '#ccc',
          borderWidth: StyleSheet.hairlineWidth,
        }}>
        {data.icon}
      </View>
      <Text style={{color: '#7a7a7a', marginTop: 10}}>{data.title}</Text>
    </TouchableOpacity>
  );
  const onMessagePress = (type, index, content) => {
    if (type === 'voice') {
      playSound(content, index);
    }
  };
  const playSound = (url, index) => {
    setVoiceLoading(true);
    if(url !='') {
      if(player) {
        console.log('I am here');
        player.destroy();
        setVoicePlaying(false);
        setVoiceLoading(false);
      }
      let playerAudio = new Player(url, { autoDestroy: true })
      .play((error) => {
        if (error) {
          console.log('failed to load the sound', error);
          setVoiceLoading(false);
          player = null
          return;
        }
        setPlayer(playerAudio);
        setVoiceLoading(false);
        setVoicePlaying(true);
      })
      .on('ended', () => {
        setPlayer(null);
        setVoicePlaying(false);
      })
    };
  };
  const _requestAndroidPermission = async() => {
    try {
      const rationale = {
        title: '麦克风权限',
        message: '需要权限录制语音.',
        buttonPositive: '确定',
      }
      const granted = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.RECORD_AUDIO, rationale)
      setHasPermission(granted === PermissionsAndroid.RESULTS.GRANTED);
    } catch (e) {
      console.log(e)
    }
  }
  const checkDir = async() => {
    if (!await RNFS.exists(`${AudioUtils.DocumentDirectoryPath}/voice/`)) {
      RNFS.mkdir(`${AudioUtils.DocumentDirectoryPath}/voice/`)
    }
  }
  const audioInitPath = async() => {
    await checkDir()
    const nowPath = `${AudioUtils.DocumentDirectoryPath}/voice/voice${Date.now()}.aac`
    setAudioPath(nowPath);
    setCurrentTime(0);
    prepareRecordingPath();
  }
  const prepareRecordingPath = () => {
    console.log('prepare============');
    AudioRecorder.requestAuthorization().then((isAuthorised) => {
      console.log('---------- isAuthorised', isAuthorised);
      AudioRecorder.prepareRecordingAtPath(audioPath, {
        SampleRate: 22050,
        Channels: 1,
        AudioQuality: 'High',
        AudioEncoding: 'aac',
        OutputFormat: 'aac_adts',
        AudioEncodingBitRate: 32000,
        MeteringEnabled: true,
      });
      AudioRecorder.onFinished = (data) => {
        // Android callback comes in the form of a promise instead.
        if (Platform.OS === 'ios') {
          _finishRecording(data.status === "OK", data.audioFileURL, data.audioFileSize);
        }
      };
    });
    
  }
  const audioProgress = () => {
    console.log('audioProgress============');
    
    AudioRecorder.onProgress = (data) => {
      setCurrentTime(Math.floor(data.currentTime));
      setAudioHandle(false);
      setVolume(Math.floor(data.currentMetering));
      random()
    }
  };
  const setAudioHandle = (status) => {
    setVoiceHandle(status);
  }
  const random = () => {
    if (timer) return
    console.log('start');
    console.log('audioHandle  ', voiceHandle);
    console.log('currrent time', currentTime);
    let timers = setInterval(()=> {
      const num =  Math.floor(Math.random() * 10)
      setVoiceVolume(num);
      setTimer(timers);
    }, 500)
  }
  const audioFinish = () => {
    console.log('------------audioFinish -------------');
    AudioRecorder.onFinished = (data) => {
      // Android callback comes in the form of a promise instead.
      if (Platform.OS === 'ios') {
        _finishRecording(data.status === "OK", data.audioFileURL, data.audioFileSize);
      }
    };
  }
  const _finishRecording = (didSucceed, filePath, fileSize) => {
    setFinished(didSucceed);
    console.warn(`Finished recording of duration ${this.state.currentTime} seconds at path: ${filePath} and size of ${fileSize || 0} bytes`);
  }
  const _record = async () => {
    console.log('record func');
    
    try {
      await AudioRecorder.startRecording()
    } catch (error) {
      console.log(error)
    }
  }
  const _stop = async () => {
    console.log('stop func');
    try {
      await AudioRecorder.stopRecording()
      console.log('_timer', timer);
      timer && clearInterval(timer);
      console.log(timer);
      if (Platform.OS === 'android') {
        _finishRecording(true)
      }
    } catch (error) {
      console.log(error)
    }
  };
  const _pause = async () => {
    try{
      await AudioRecorder.pauseRecording() // Android 由于API问题无法使用此方法
    }catch (e) {
      console.log(e)
    }
  }
  const _resume = async () => {
    try{
      await AudioRecorder.resumeRecording() // Android 由于API问题无法使用此方法
    }catch (e) {
      console.log(e)
    }
  }
  const receive = () => {
    const newMsg = [...messages]
    newMsg.push(
      {
        id: `${new Date().getTime()}`,
        type: 'text',
        content: '收到一条消息' + new Date().getTime(),
        targetId: '12345678',
        chatInfo: {
          avatar: require('./assets/images/avatar.png'),
          id: '88886666',
          nickName: 'Test'
        },
        renderTime: true,
        sendStatus: 1,
        time: `${new Date().getTime()}`
      })
    this.setState({ messages: newMsg })
  }

  return (
    <View style={styles.container}>
      <ChatScreen 
        messageList={messages}
        chatBackgroundImage={chatBg}
        panelSource={panelSource}
        renderPanelRow={renderPanelRow}
        inverted={inverted}
        sendMessage={sendMessage}
        onMessagePress={onMessagePress}
        voiceLoading={voiceLoading}
        voicePlaying={voicePlaying}
        requestAndroidPermission={_requestAndroidPermission}
        checkPermission={AudioRecorder.requestAuthorization}
        audioHasPermission={hasPermission}
        audioPath={audioPath}
        audioInitPath={audioInitPath}
        audioOnProgress={audioProgress}
        audioOnFinish={audioFinish}
        audioRecord={_record}
        audioStopRecord={_stop}
        audioPauseRecord={_pause}
        audioResumeRecord={_resume}
        audioCurrentTime={currentTime}
        audioHandle={voiceHandle}
        voiceVolume={voiceVolume}
      />
      <TouchableOpacity
        onPress={() => receive()}
        style={{width: 60,
          height: 60, borderRadius: 30,
          position: 'absolute', top: 200, right: 0, backgroundColor: 'blue',
          justifyContent: 'center',
          alignItems: 'center'
        }}>
        <Text style={{color: '#fff'}}>
          模拟收消息
        </Text>
      </TouchableOpacity>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
});

export default App;

**Comment by rising32** [comment]
I am very attracted to your package...
So I am going to implement your package in my project( image and voice chat)  now.
But I think your package is not suitable  to the recent React version - exactly react lifecycle....

I committed my code and error above.... please help me....
I'll use and advertise this in future... Good Package!

**Comment by DaiYz** [comment]
can u tell me the version of react native ?

**Comment by DaiYz** [comment]
please wait
