### ISSUE TITLE
About Props of ChatScreen

### ISSUE THREAD

**Issue by rising32** [DaiYz/react-native-easy-chat-ui#53]
There are many props in your module...
       <ChatScreen
          ref={e => (this.chat = e)}
          CustomImageComponent={FastImage}
          messageList={this.state.messages}
          sendMessage={this.sendMessage}
          // chatBackgroundImage={this.state.chatBg}
          inverted={this.state.inverted}
          panelSource={this.state.panelSource}
          renderPanelRow={this.renderPanelRow}
          onMessagePress={this.onPress}
          voiceLoading={this.state.voiceLoading}
          voicePlaying={this.state.voicePlaying}
          audioPath={this.state.audioPath}
          audioHasPermission={this.state.hasPermission}
          requestAndroidPermission={this._requestAndroidPermission}
          audioOnProgress={this.audioProgress}
          audioOnFinish={this.audioFinish}
          audioInitPath={this.initPath}
          audioRecord={this._record}
          audioStopRecord={this._stop}
          audioCurrentTime={15}
          audioHandle={this.state.audioHandle}
          setAudioHandle={this.setAudioHandle}
          voiceVolume={this.state.voiceVolume}
        />
I built my project with your package, then I can observe as followings...

executed order  audioOnProgress -> audioOnFinish -> audioRecord -> audioStopRecord...
 I think 'audioOnFinish '  have to execute at the end...
Please tell me about your opinion....

![image](https://user-images.githubusercontent.com/29010143/71722158-e9a81180-2e62-11ea-9396-d685e33c1c76.png)

**Comment by DaiYz** [comment]
Please provide your code about audio recording
