### ISSUE TITLE
RNC View Pager version conflict

### ISSUE THREAD

**Issue by tayguohong** [DaiYz/react-native-easy-chat-ui#55]
In my project, i am having View Pager version 3.3.0 while in your library, the view pager version is 2.0.1. Hence causing error Tried to register two views with the same name RNCViewPager. Any idea how to resolve this issue?

**Comment by DaiYz** [comment]
I use version 3.3.0 in example,  can u check it again?

**Comment by tayguohong** [comment]
> I use version 3.3.0 in example, can u check it again?
but i checked in package.json in ur library, u used version 2.0.1

![image](https://user-images.githubusercontent.com/57252173/73631284-7a0c8880-4693-11ea-941a-84bd4b413c2b.png)

**Comment by DaiYz** [comment]
fixed
