### ISSUE TITLE
滑动聊天记录有时失效

### ISSUE THREAD

**Issue by junjun16818** [DaiYz/react-native-easy-chat-ui#6]
在chatview的 render中 <TouchableOpacity> 会导致有时滑动失效 至少在安卓上是这样的
改成View 会修复

其实我想表达的不是上面写的 我想表达的是 这个项目真的很牛逼

**Comment by DaiYz** [comment]
@junjun16818 欢迎👏提供PR

**Comment by DaiYz** [comment]
已修复
