### ISSUE TITLE
Error: LogBox must be enabled before AppContainer is required so that it can properly wrap the console methods.

### ISSUE THREAD

**Issue by inkCrazy** [DaiYz/react-native-easy-chat-ui#60]
"react-native-easy-chat-ui": "^0.4.9",
   "react": "16.11.0",
    "react-native": "0.62.2",

![image](https://user-images.githubusercontent.com/12253453/86567685-57fa9780-bf9e-11ea-9d20-9b1a2f594c71.png)

好像是TopView的问题，我单独复制teaset里面的组件Toast到我的项目里面，也是这个报错。

**Comment by DaiYz** [comment]
我电脑跑不了0.62 的版本，实属蛋疼，你google先看看

**Comment by inkCrazy** [comment]
<img width="513" alt="AE1AFDD0-C569-40B5-9C08-E9593818485C" src="https://user-images.githubusercontent.com/12253453/87394884-fad89480-c5e2-11ea-8fb1-35328884d890.png">
我把require('react-native').unstable_enableLogBox();   注释掉就好了，蛋疼！

**Comment by DaiYz** [comment]
这个是62自带的吗？

**Comment by inkCrazy** [comment]
应该是吧，之前没见过

**Comment by DaiYz** [comment]
升级到最新版本就没这个问题了，62bug太多
