### ISSUE TITLE
Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`

### ISSUE THREAD

**Issue by sweet-xincome** [DaiYz/react-native-easy-chat-ui#64]
"react": "16.13.1",
"react-native": "0.63.1",
"react-native-easy-chat-ui": "^0.4.10",

![image](https://user-images.githubusercontent.com/46555207/88381057-40ae0d80-cdd8-11ea-9b5c-174d2c02bdf3.png)

**Comment by DaiYz** [comment]
先不管这个，不知道为啥去掉默认值

**Comment by fangcaiwen** [comment]
+1

**Comment by cquptzsn** [comment]
+1
