### ISSUE TITLE
双方同时发送语音消息，多次发送之后，iOS端的语音录入动画延迟了

### ISSUE THREAD

**Issue by sky1990** [DaiYz/react-native-easy-chat-ui#65]
用您的这个ui，我发现双方同时发送语音消息，多次发送之后，会出现iOS端在松开手指发送消息时，语音录入动画延迟了取消，语音录入还在继续，过几秒之后才能正常，这个能解决吗

**Comment by DaiYz** [comment]
你能定位到问题吗

**Comment by DaiYz** [comment]
我会将方法单独剥离出来，这样你们可以自己替换
