### ISSUE TITLE
下拉加载设置了  inverter={true} 不触发

### ISSUE THREAD

**Issue by lenglengtaidu** [DaiYz/react-native-easy-chat-ui#67]

**Comment by lenglengtaidu** [comment]
![image](https://user-images.githubusercontent.com/46698833/89971237-4ab38580-dc8d-11ea-896d-72f6498f9e62.png)

**Comment by DaiYz** [comment]
loadHistory 吗

**Comment by lenglengtaidu** [comment]
现在可以了。 请问有没有加载动画？

**Comment by DaiYz** [comment]
renderLoadEarlier 这个属性可以自定渲染动画
