### ISSUE TITLE
案例中安卓中语音不能使用？

### ISSUE THREAD

**Issue by jetBn** [DaiYz/react-native-easy-chat-ui#68]
案例中安卓中语音不能使用？

**Comment by DaiYz** [comment]
你看看是否报错了

**Comment by jetBn** [comment]
> 你看看是否报错了

![image](https://user-images.githubusercontent.com/26957220/90102585-858fe900-dd73-11ea-8f3f-e104f1deee90.png)

**Comment by DaiYz** [comment]
你具体核实下这个录音的库 react-native-audio， 如果不行的话，你可以换个别的录音
