### ISSUE TITLE
源码中的example如何运行呢

### ISSUE THREAD

**Issue by jiangwalle** [DaiYz/react-native-easy-chat-ui#69]
您好，问一个小白的问题。请问，源码工程中的example应该如何运行呢？当cd到example目录下，yarn install，之后，发现example工程没有引入react-native-easy-chat-ui，启动时会报错。

请问，这里是有意为之吗？还是我的运行方式不正确呢？

谢谢。

模拟器错误截图：
![image](https://user-images.githubusercontent.com/8231736/92381411-ea661580-f15e-11ea-8c4a-25ffba428c9c.png)

**Comment by DaiYz** [comment]
你在example 下面先安装下 这个库就好了
