### ISSUE TITLE
发送图片无法立刻发送,需要点击屏幕

### ISSUE THREAD

**Issue by angleshe** [DaiYz/react-native-easy-chat-ui#70]
数据push进messageList后没有立刻渲染需要在触摸一下屏幕才渲染
 "react": "16.13.1",
 "react-native": "0.63.2",

**Comment by angleshe** [comment]
发送位置也一样push进messageList中还要触摸一下才能执行renderLocationMessage

**Comment by DaiYz** [comment]
你检查下是不是数据的指针问题

**Comment by angleshe** [comment]
谢谢  刚刚查了 确实指针问题
