### ISSUE TITLE
ios端显示不了头像和按钮图片

### ISSUE THREAD

**Issue by houta-higuchi** [DaiYz/react-native-easy-chat-ui#72]
![image](https://user-images.githubusercontent.com/26084826/96361292-ff1ecb80-1156-11eb-82ec-4fe6811dfd0e.png)

**Comment by houta-higuchi** [comment]
ios13可以，ios14不行

**Comment by houta-higuchi** [comment]
解决了，要在原生加下代码  
![image](https://user-images.githubusercontent.com/26084826/96361493-c54ec480-1158-11eb-89a6-171b7e977343.png)

**Comment by DaiYz** [comment]
这个是RN的问题，你升级下
