### ISSUE TITLE
如果没给录音权限，点击录音按钮会闪退

### ISSUE THREAD

**Issue by yz1311** [DaiYz/react-native-easy-chat-ui#73]
即使`audioHasPermission ` `requestAndroidPermission` `checkPermission` 都已经赋值了

**Comment by DaiYz** [comment]
前端可以捕获下这个错误，看看是否是录音库从原生方面的报错

**Comment by yz1311** [comment]
是录音库报错，但是即使没权限时，audioRecord这个回调依旧会触发,即使在回调方法里面不调用录音，那个录音的loading早已显示

**Comment by DaiYz** [comment]
嗯，我看了下这块逻辑确实有点问题，我有空调整下
