### ISSUE TITLE
ChatItem 有严重的效率问题

### ISSUE THREAD

**Issue by junjun16818** [DaiYz/react-native-easy-chat-ui#8]
在聊天页面任何操作都会导致 ChatItem 重新渲染 比如切换文字和键盘
在聊天记录多的时候会导致卡顿严重

```

import { observer } from 'mobx-react/native';
@observer
    export default class ChatItem extends Component 
```

加入mobx 可以解决这个问题

因为项目已经被我改的面目全非 所以暂时没有办法PR

**Comment by DaiYz** [comment]
嗯，mobx会有一层浅对比。看来PureComponent 用处并不大，我会优化这部分的代码，谢谢你的意见

**Comment by DaiYz** [comment]
监测了下Demo, 发现除了弹出多选按钮以外没有重绘现象，请提供下你的版本 😂

**Comment by junjun16818** [comment]
我使用的版本是比较旧的 没有使用PureComponent

**Comment by DaiYz** [comment]
嗯。。你更新到最新版就好了👏
