### ISSUE TITLE
布局问题

### ISSUE THREAD

**Issue by yanhongchang-1105** [DaiYz/react-native-easy-chat-ui#80]
使用了inverted 做上拉加载 但是消息少的话  在页面底部显示第一条消息怎么解决 （可就是底部显示消息 上部分空白）

**Comment by DaiYz** [comment]
自己坐下判断

**Comment by yanhongchang-1105** [comment]
您的意思是通过内容高度动态判断inverted吗




| |
闫洪昌
|
|
***@***.***
|

签名由 网易邮箱大师 定制

在2021年03月16日 22:53，DaiYz 写道：

自己坐下判断

**Comment by DaiYz** [comment]
大致是这么个意思
