### ISSUE TITLE
New case crash app when messageList is empty or undefined

### ISSUE THREAD

**Issue by khangvuong97** [DaiYz/react-native-easy-chat-ui#83]
I have connect my list message with redux through props.
Error: "messageList.slice is not a function"
Should we have check out this case. Thank you!
![image](https://user-images.githubusercontent.com/33254045/114165794-22347600-9957-11eb-9760-ec2cca27a0e0.png)

**Comment by DaiYz** [comment]
messageList must be an array or []

**Comment by khangvuong97** [comment]
> messageList must be an array or []

Thank you. It's my mistake
